### ISSUE TITLE
ssh

### ISSUE THREAD

**Issue by synsan123** [brkim92/Team_project#1]
mkdir dataset
mv annotations/ dataset/
mv images/ dataset/
otx build Custom_Object_Detection_Gen3_ATSS --train-data-roots /home/kyj/American/dataset/
cd otx-workspace-DETECTION
otx train

ssh team002@61.108.166.16
busan@123
Workspace path : /home/team002/workspace/kyj

scp -r ./American/ team002@61.108.166.16:/home/team002/workspace/kyj

cp images1.jpeg ~/workspace/kyj/otx-workspace-DETECTION/outputs/deploy/python/
cd ~/workspace/kyj/otx-workspace-DETECTION/outputs/deploy/python/
python3 demo.py -i ./images1.jpeg -l

**Comment by StarTTearS** [comment]
good
